######################################################################
# Automatically generated by qmake (3.0) ven. avr. 29 10:00:57 2016
######################################################################

TEMPLATE = app
TARGET = tryQt
INCLUDEPATH += .

QT+=widgets

# Input
SOURCES  = main.cpp \
           mainwindow.cpp \ 
           mother.cpp

HEADERS  = mainwindow.h \
           mother.h
